Repository giorgosart/react-easy-edit, pull requests merged in 2019-03, with the labels that each got.

#4 Issue #2 - Fix to comma-separate selected checkbox values
  src/lib/EasyEdit.jsx
  src/lib/EasyEdit.test.js
Labels: bug, missing tests

#7 #6 Introduced a new prop called 'allowEdit' to be used to determine i a component should be editable or not
  .idea/workspace.xml
  README.md
  src/demo/App.js
  src/lib/EasyEdit.jsx
  src/lib/EasyEdit.test.js
Labels: enhancement

#8 Fix #5 - Passed in value is now displayed when editing
  src/lib/EasyEdit.jsx
  src/lib/EasyEdit.test.js
Labels: bug

#10 #9 Introduced onValidate and validationMessage prop to allow users to pass in a way to validate the user's input
  README.md
  src/demo/App.js
  src/lib/EasyEdit.css
  src/lib/EasyEdit.jsx
  src/lib/EasyEdit.test.js
  src/lib/EasyInput.jsx
  src/lib/EasyInput.test.js
  src/lib/globals.js
Labels: enhancement

#14 #13 Changed the cursor to not-allowed when the prop allowEdit is set to false
  src/demo/App.js
  src/lib/EasyEdit.css
  src/lib/EasyEdit.jsx
  src/lib/EasyEdit.test.js
Labels: enhancement

#15 #12 External change to the value prop now reflected in EasyEdit state.value
  src/lib/EasyEdit.jsx
Labels: bug

#17 #16 added support for 'range' type
  README.md
  src/demo/App.js
  src/lib/EasyEdit.jsx
Labels: enhancement
